---
# This workflow requires a GALAXY_API_KEY secret present in the GitHub
# repository or organization.

name: Release
'on':
  push:
    branches:
      - 'main'

env:
  ROLE_NAME: android_studio

defaults:
  run:
    working-directory: "diademiemi.$env:ROLE_NAME"

jobs:

  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2
        with:
          path: "diademiemi.$env:ROLE_NAME"

      - name: Set up Python 3.
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Ansible.
        run: pip3 install ansible-core

      - name: Trigger a new import on Galaxy.
        run: >-
          ansible-galaxy role import --api-key ${{ secrets.GALAXY_API_KEY }} --role-name $env:ROLE_NAME
          $(echo ${{ github.repository }} | cut -d/ -f1) $(echo ${{ github.repository }} | cut -d/ -f2)
